db.restaurantes.find({})
db.restaurantes.find({}, { "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1})
db.restaurantes.find({}, { "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "_id": 0})
db.restaurantes.find({}, { "restaurant_id": 1, "name": 1, "borough": 1, "zipcode": 1, "_id": 0 })
db.restaurantes.find({ "borough": "Bronx" })..pretty()
db.restaurantes.find({ "borough": "Bronx" }).limit(5)..pretty()
db.restaurantes.find({ "borough": { "$ne": "Bronx" } }).skip(5).limit(5).pretty()
db.restaurantes.find({ "grades.score": { "$gt": 90 } }).pretty()
db.restaurantes.find({ "grades.score": { "$gt": 80, "$lt": 100 } })/*dejo de utilizar pretty ya que en mongosh no es necesario*/
db.restaurantes.find({ "address.coord.0": { "$lt": -95.754168 } })
db.restaurantes.find({ "cuisine": { "$ne": "American" }, "grades.score": { "$gt": 70 }, "address.coord.1": { "$lt": -65.754168 }})
db.restaurantes.find({ "cuisine": { "$ne": "American" }, "grades.score": { "$gt": 70 }, "address.coord.1": { "$lt": -65.754168 }})/*no use and antes */
db.restaurantes.find({ "cuisine": { "$ne": "American " },"grades.grade": "A","borough": { "$ne": "Brooklyn" }}).sort({ "cuisine": -1 })
db.restaurantes.find({ "name": { "$regex": /^Wil/i }}, {"restaurant_id": 1,"name": 1,"borough": 1,"cuisine": 1,"_id": 0})
db.restaurantes.find({ "name": { $regex: /ces$/, $options: 'i' } },{ "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "_id": 0 })
db.restaurantes.find({ "name": { $regex: /Reg/, $options: 'i' } },{ "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "_id": 0 })
db.restaurantes.find({ "borough": "Bronx","cuisine": { $in: ["American", "Chinese"] }},{"restaurant_id": 1,"name": 1,"borough": 1,"cuisine": 1,"_id": 0})
db.restaurantes.find({"borough": { $in: ["Staten Island", "Queens", "Bronx", "Brooklyn"] }},{"restaurant_id": 1,"name": 1,"borough": 1,"cuisine": 1,"_id": 0})
db.restaurantes.find({"borough": {$nin: ["Staten Island", "Queens", "Bronx", "Brooklyn"]}},{"restaurant_id": 1,"name": 1,"borough": 1,"cuisine": 1,"_id": 0})
db.restaurantes.find({"grades.score": { $lt: 10 }},{"restaurant_id": 1,"name": 1,"borough": 1,"cuisine": 1,"_id": 0})
db.restaurantes.find({ "cuisine": "Seafood", $nor: [ { "cuisine": "American" }, { "cuisine": "Chinese" }, { "name": { $regex: /^Wil/i } } ] }, { "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "_id": 0 })
